### ISSUE TITLE
LookML Validation facing Unexpected REad 

### ISSUE THREAD

**Issue by enrique-villarrealp** [spectacles-ci/spectacles#725]
<img width="1007" alt="image" src="https://github.com/spectacles-ci/spectacles/assets/85933898/29fd4361-3a81-42f2-a494-0df1019ca626">

We've started facing this weird issue, somewhat inconsistently.  Some PRs are triggering it, some PRs aren't. Has anyone faced this before?

One PR seemed to fix this by adding an unrelated LAMS exception, though I'm not sure why this would happen.

**Comment by enrique-villarrealp** [comment]
Forcing the CI jobs to run in debug mode doesn't point to any issue, but does make the CI successful...

**Comment by enrique-villarrealp** [comment]
Could this be because of the concurrency problem? Having multiple PRs trigger the check at once

**Comment by DylanBaker** [comment]
@enrique-villarrealp, would you mind sharing the full logs from a run when running in verbose `-v` mode please?

This isn't behaviour we have seen before. It could theoretically be due to concurrency. It's possible that Looker doesn't like the same user running two LookML validations simultaneous (or that the changing of the branch mid-validation is causing the issue). As we talk about in our docs, we can't really support multiple simultaneous runs with the same user's credentials because of how Looker handles it.

**Comment by LProcopi15** [comment]
@DylanBaker we're running into the same issue. Similar to @enrique-villarrealp this issue is only happening intermittently. To recreate, I opened a new branch and edited some LookML. No one else on the team has run the CI job since yesterday and no one else on the team is working off of this branch, so there should not be an issue with concurrency.

On the first CI run the job on my new branch, the CI failed. I ran in verbose mode and here are the logs:

![image](https://github.com/spectacles-ci/spectacles/assets/7942620/7d2b5fae-471a-4e41-a8ce-6b625554109f)
![image](https://github.com/spectacles-ci/spectacles/assets/7942620/6cf53640-9658-4d3a-8063-eeb37f9e45ff)
![image](https://github.com/spectacles-ci/spectacles/assets/7942620/73b83dcb-48f5-46ca-ac23-4fb36543e0cd)

I then re-triggered a run of the job in Github and it ran without error.

### Some Additional Context
<details>
<summary>Here's the contexts of our Github action yml</summary>

  ```
  name: Spectacles CI Run
  
  on:
    pull_request:
      paths:
        - 'looker/**.lkml'
    workflow_dispatch:
  
  concurrency:
    group: spectacles-validate
    cancel-in-progress: true
  
  jobs:
    spectacles-validate:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
          working-directory: dbt
  
      env:
        HEAD_REF: ${{ github.head_ref }}
        LOOKER_BASE_URL: ${{ secrets.LOOKER_BASE_URL }}
        LOOKER_CLIENT_ID: ${{ secrets.LOOKER_CLIENT_ID }}
        LOOKER_CLIENT_SECRET: ${{ secrets.LOOKER_CLIENT_SECRET }}
  
      steps:
        - uses: actions/checkout@v3
  
        - uses: actions/setup-python@v4
          with:
            python-version: 3.9
  
        - name: Install dependencies
          run: pip install spectacles pydantic==1.10.9
  
        - name: Validate LookML Syntax
          run: bash ../etc/ci.run-spectacles-lookml.sh
  ```
</details>

<details>
<summary>Here's the contexts of ci.run-spectacles-lookml.sh referenced in the action yml</summary>

  ```
      spectacles lookml \
          --base-url ${LOOKER_BASE_URL} \
          --client-id ${LOOKER_CLIENT_ID} \
          --client-secret ${LOOKER_CLIENT_SECRET} \
          --project replicated \
          --branch ${HEAD_REF} \
          -v
  ```
</details>


Any thoughts on what might be causing this?
